ivt = ["", # stack_top
"Reset_Handler",
"NMI_Handler",
"HardFault_Handler",
"MemManage_Handler",
"BusFault_Handler",
"UsageFault_Handler",
"",
"",
"",
"",
"SVC_Handler",
"DebugMon_Handler",
"",
"PendSV_Handler",
"SysTick_Handler",
"WWDG_IRQHandler",
"LVD_IRQHandler",
"RTC_IRQHandler",
"FLASH_IRQHandler",
"RCC_IRQHandler",
"EXTI0_1_IRQHandler",
"EXTI2_3_IRQHandler",
"EXTI4_15_IRQHandler",
"TSI_IRQHandler",
"DMA_Channel0_IRQHandler",
"DMA_Channel1_2_IRQHandler",
"DMA_Channel3_4_IRQHandler",
"ADC_IRQHandler",
"TIMER0_BRK_UP_TRG_COM_IRQHandler",
"TIMER0_CC_IRQHandler",
"TIMER1_IRQHandler",
"TIMER2_IRQHandler",
"TIMER5_DAC_IRQHandler",
"",
"TIMER13_IRQHandler",
"TIMER14_IRQHandler",
"TIMER15_IRQHandler",
"TIMER16_IRQHandler",
"I2C0_IRQHandler",
"I2C1_IRQHandler",
"SPI0_IRQHandler",
"SPI1_IRQHandler",
"USART0_IRQHandler",
"USART1_IRQHandler",
"",
"CEC_IRQHandler",
"",
"I2C0_ER_IRQHandler",
"",
"I2C1_ER_IRQHandler",
"I2C2_IRQHandler",
"I2C2_ER_IRQHandler",
"USBD_LO_IRQHandler",
"USBD_HI_IRQHandler",
"",
"",
"",
"USBD_WAKEUP_IRQHandler",
"",
"",
"",
"",
"",
"DMA_Channel5_6_IRQHandler",
"",
"",
"SPI2_IRQHandler",
]

#tableAddr = 0x08002c00
tableAddr = 0x08000000

for (id, name) in enumerate(ivt):
    if (name):
        print(name,hex(tableAddr+(id*4)),"l")